services:
  database:
    image: 'postgres:17-alpine'
    ports:
      - "15432:5432"
    env_file:
      - .env.docker
    networks:
      - postgres-network
    volumes:
      - .db/db-data/:/var/lib/postgressql/data
      - .db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge